name: Test file
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{vars.registry}}
          echo ${{vars.registry_url}}
          echo ${{vars.registry_id}}
          echo ${{vars.username}}
          echo ${{vars.password}}
      - if: ${{ vars.registry }} == "ecr"
        uses: unfor19/install-aws-cli-action@v1
      - if: ${{ vars.registry }} == "ecr"
        run: |
          aws configure set aws_access_key_id ${{ vars.username }}
          aws configure set aws_secret_access_key ${{ vars.password }}
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{vars.registry_url}}
        shell: "bash"
      - if: ${{vars.registry}} != "ecr"
        run: |
          echo ${{vars.password}} | docker login --username ${{vars.username}} --password-stdin ${{vars.registry_url}}
        shell: "bash"
      
     
  
