name: 'Push images with apps'
on: workflow_dispatch
jobs:
  test:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "::error::Test message"
          echo ${{ vars.BRANCH_NAME }}
          var=NAME
          if [[ "${{ secrets.NAME }}" == 'main' ]];
          then
            echo 'MAIN'
          else
            echo 'NOT_MAIN'
          fi
      - uses: actions/upload-artifact@v3
        with:
          name: test_dir
          path: test/
  test_artifacts:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: test_ramprin
      - uses: actions/download-artifact@v3
        with:
          name: test_dir
          path: test
      - run: |
          ls
          for d in test/*.txt
          do
            mv test/$d .
          done
          ls
