name: 'Push images with apps'
on: workflow_dispatch
jobs:
  test:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ vars.BRANCH_NAME }}
          var=NAME
          if [[ "${{ secrets.$var }}" == 'main' ]];
          then
            echo 'MAIN'
          else
            echo 'NOT_MAIN'
          fi
