name: Test file
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ env.registry }} == "ecr"
        uses: unfor19/install-aws-cli-action@v1
      - if: ${{ env.registry }} == "ecr"
        run: |
          aws configure set aws_access_key_id ${{ env.username }}
          aws configure set aws_secret_access_key ${{ env.password }}
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{env.registry_url}}
        shell: "bash"
      - if: ${{env.registry}} != "ecr"
        run: |
          echo ${{env.password}} | docker login --username ${{env.username}} --password-stdin ${{env.registry_url}}
        shell: "bash"
      - run: |
          export REG="${{env.registry_url}}/${{env.registry_id}}"
          dirs=*/
          for dir in $dirs
          do
          name=$(basename $dir)
          if [[ -e $dir ]] && [[ $name != .* ]] && [[ -f $name/Dockerfile ]];
            then
              echo "Make image from $name/Dockerfile"
              docker build -t $REG/$name:${{github.sha}} \
                            -t $REG/$name:latest $dir
              if [[ ${{env.registry == "ecr" ]];
                then
                          aws ecr-public describe-repositories --repository-names $name --region us-east-1 || aws ecr-public create-repository --repository-name $name --region us-east-1
                fi
                    docker push --all-tags $REG/$name
            fi
          done
        shell: "bash"
      - run: |
          docker logout
        shell: "bash"
  
