name: Test file
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{vars.registry}}
          echo ${{vars.registry_url}}
          echo ${{vars.registry_id}}
          echo ${{vars.username}}
          echo ${{vars.password}}
      - uses: unfor19/install-aws-cli-action@v1
      - name: If ECR login
        run: |
          if [[ ${{ vars.registry }} == "ecr" ]];
          then
            aws configure set aws_access_key_id ${{ vars.username }}
            aws configure set aws_secret_access_key ${{ vars.password }}
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{vars.registry_url}}
          fi
        shell: "bash"
      - name: If not ECR login
        run: |
          if [[ ${{vars.registry}} != "ecr" ]];
          then
            echo ${{vars.password}} | docker login --username ${{vars.username}} --password-stdin ${{vars.registry_url}}
          fi
        shell: "bash"
      - name: Build&Push
        run: |
          export REG="${{vars.registry_url}}/${{vars.registry_id}}"
          dirs=*/
          for dir in $dirs
          do
          name=$(basename $dir)
          if [[ -e $dir ]] && [[ $name != .* ]] && [[ -f $name/Dockerfile ]];
            then
              echo "Make image from $name/Dockerfile"
              docker build -t $REG/$name:${{github.sha}} \
                            -t $REG/$name:latest $dir
              if [[ ${{vars.registry == "ecr" ]];
                then
                          aws ecr-public describe-repositories --repository-names $name --region us-east-1 || aws ecr-public create-repository --repository-name $name --region us-east-1
                fi
                    docker push --all-tags $REG/$name
            fi
          done
        shell: "bash"
      
     
  
