name: 'Push images with apps'
on: workflow_dispatch
jobs:
  test:
    environment: not_main
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ vars.BRANCH_NAME }}
          if [[ ${{ secrets.NAME }} == 'main' ]];
          then
            echo 'MAIN'
          else
            echo 'NOT_MAIN'
          fi
